### ISSUE TITLE
打开混淆后崩溃

### ISSUE THREAD

**Issue by Qdafengzi** [jenly1314/ZXingLite#164]
自定义的扫描界面继承CaptureActivity，关闭混淆后就没事，打开就崩溃，混淆按照项目添加的。
编码环境：Kotlin  
编译器版本： Android Studio Arctic Fox

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{***.activity.QRCodeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3483)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3655)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7879)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
        at com.king.zxing.DefaultCameraScan.initData(SourceFile:144)
        at com.king.zxing.DefaultCameraScan.<init>(SourceFile:107)
        at com.king.zxing.CaptureActivity.initCameraScan(SourceFile:86)
        at ***activity.QRCodeActivity.initCameraScan(SourceFile:31)
        at com.king.zxing.CaptureActivity.initUI(SourceFile:71)
        at com.king.zxing.CaptureActivity.onCreate(SourceFile:52)
        at ***.activity.QRCodeActivity.onCreate(SourceFile:18)
        at android.app.Activity.performCreate(Activity.java:8093)
        at android.app.Activity.performCreate(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3456)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3655) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:7879) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
```

**Comment by Qdafengzi** [comment]
是自己搞错了

**Comment by Qdafengzi** [comment]
是我自己搞错了
