### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by zmyqucai8** [jenly1314/ZXingLite#26]
`  java.lang.ArrayIndexOutOfBoundsException: length=1382400; index=1383479
                                                                    at com.king.zxing.DecodeHandler.decode(DecodeHandler.java:80)
                                                                    at com.king.zxing.DecodeHandler.handleMessage(DecodeHandler.java:57)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at com.king.zxing.DecodeThread.run(DecodeThread.java:111)`

**Comment by jenly1314** [comment]
因为目前很多机型已经适配，你光贴一个下标越界的异常无法确定具体原因，请详细描述，机型，版本，使用方式等相关使用场景。

**Comment by zmyqucai8** [comment]
AS自带模拟器
系统8.0  ，API 26

使用demo APP 直接闪退，日志如上。

**Comment by jenly1314** [comment]
扫码你使用模拟器？-_-||，模拟器的拍摄相关的功能压根就没用，请使用真机吧、

**Comment by gfeng567** [comment]
李云龙：你他娘的真是个人才。。
