### ISSUE TITLE
Open, close Flash exception

### ISSUE THREAD

**Issue by thapld** [jenly1314/ZXingLite#40]
Here cause when I clicked flash image:

Caused by: java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2102)
        at com.king.zxing.app.CustomActivity.openFlash(CustomActivity.java:107)
        at com.king.zxing.app.CustomActivity.clickFlash(CustomActivity.java:130)
        at com.king.zxing.app.CustomActivity.onClick(CustomActivity.java:142)

How can I resolve the exception? Thanks so much.

**Comment by jenly1314** [comment]
Make sure your phone supports flash.
```java
    public boolean hasTorch(Context context){
        return context.getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_FLASH);
    }
```

**Comment by thapld** [comment]
It's work. I will close the issue. Thank you so much.
