### ISSUE TITLE
Oppo R9s打不开相机，跳转后二维码扫描框显示正在扫描，背景一片黑，控制台报错如下

### ISSUE THREAD

**Issue by zhoushunli** [jenly1314/ZXingLite#47]
java.lang.RuntimeException: getParameters failed (empty parameters)
        at android.hardware.Camera.native_getParameters(Native Method)
        at android.hardware.Camera.getParameters(Camera.java:2027)
        at com.king.zxing.camera.AutoFocusManager.<init>(AutoFocusManager.java:54)
        at com.king.zxing.camera.CameraManager.startPreview(CameraManager.java:156)
        at com.king.zxing.CaptureActivityHandler.<init>(CaptureActivityHandler.java:75)
        at com.king.zxing.CaptureActivity.initCamera(CaptureActivity.java:786)
        at com.king.zxing.CaptureActivity.surfaceCreated(CaptureActivity.java:427)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6126)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by jenly1314** [comment]
麻烦问一下ZXingLite你使用的哪个版本，CaptureActivity目前没有这么多行，描述详细点，我好定位。

**Comment by zhoushunli** [comment]
不好意思，近期事情太多，推迟这么久才回复，望见谅，我用的版本是1.0.6版本，然后最近的gp后台监测有一个新的空指针，日志如下：
java.lang.RuntimeException: 
  at android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:4009)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:3975)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:3949)
  at android.app.ActivityThread.handlePauseActivity (ActivityThread.java:3923)
  at android.app.ActivityThread.-wrap15 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1642)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6626)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)
Caused by: java.lang.NullPointerException: 
  at com.king.zxing.CaptureActivity.onPause (CaptureActivity.java:318)
  at android.app.Activity.performPause (Activity.java:7176)
  at android.app.Instrumentation.callActivityOnPause (Instrumentation.java:1430)
  at android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:3998)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:3975)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:3949)
  at android.app.ActivityThread.handlePauseActivity (ActivityThread.java:3923)
  at android.app.ActivityThread.-wrap15 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1642)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6626)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)

我是用的gradle引入的
 classpath 'com.android.tools.build:gradle:3.2.1'

麻烦有空的时候帮忙看下，谢谢了

**Comment by jenly1314** [comment]
查看1.0.6历史版本记录，根据你发的报错信息定位是SurfaceView 空指针导致的？
建议最好是升级到目前最新版本，然后测试并定位，看此问题是否依然存在。

**Comment by zhoushunli** [comment]
> 查看1.0.6历史版本记录，根据你发的报错信息定位是SurfaceView 空指针导致的？
> 建议最好是升级到目前最新版本，然后测试并定位，看此问题是否依然存在。

好的，我会试一下的，谢谢回复

**Comment by houyidg** [comment]
大哥，google了一下，是因为你这个ondestory 销毁camera的时候是调用子线程。反复进入的时候就会初始化失败而崩溃。坑

**Comment by houyidg** [comment]
还有就是你这个初始化camera比我用腾讯的人脸识别初始化慢了400ms左右
