### ISSUE TITLE
引入androidX版本，android 8.0 启动崩溃

### ISSUE THREAD

**Issue by weiwenqiang** [jenly1314/ZXingLite#93]
引用上9.0以上正常，8.0启动崩溃，去掉应用，程序正常，报错没有直接指向，反复测试引用，是二维码库的问题

java.lang.RuntimeException: Unable to instantiate application com.tencent.shadow.sample.host.HostApplication: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.host.HostApplication" on path: DexPathList[[zip file "/data/app/com.zzz.myemergencyclientnew-H7jLGC8js5K1shfiL5nCYw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zzz.myemergencyclientnew-H7jLGC8js5K1shfiL5nCYw==/lib/arm, /data/app/com.zzz.myemergencyclientnew-H7jLGC8js5K1shfiL5nCYw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1059)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6590)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.host.HostApplication" on path: DexPathList[[zip file "/data/app/com.zzz.myemergencyclientnew-H7jLGC8js5K1shfiL5nCYw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zzz.myemergencyclientnew-H7jLGC8js5K1shfiL5nCYw==/lib/arm, /data/app/com.zzz.myemergencyclientnew-H7jLGC8js5K1shfiL5nCYw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1053)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6590) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by weiwenqiang** [comment]
抱歉，经过数天的调试，最终定位问题，是我踩了大坑，大家引以为戒

then you are telling android to use java 8.

then the problem happens if you are using a library that does not support java 8 (i.e it uses something from java 7 that is not allowed in java 8)

for me the problem happens because I had the following in my gradle

implementation 'com.google.code.gson:gson:2.8.6'

which seems not to support java 8 , I have solved it be removing the Gson library and used moshi instead of it for json to model parsing

**Comment by gavindst** [comment]
我也遇到了相同的问题,Android6.0空的项目导入后报错
我用的是openjdk-11我更改jdk版本为1.8还是不行.
下载demo运行一切正常
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.store.scanbarcode, PID: 5126
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.store.scanbarcode/com.store.scanbarcode.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.store.scanbarcode.MainActivity" on path: DexPathList[[zip file "/data/app/com.store.scanbarcode-5mePmYbDwc3RwRoad7s37A==/base.apk"],nativeLibraryDirectories=[/data/app/com.store.scanbarcode-5mePmYbDwc3RwRoad7s37A==/lib/x86, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.store.scanbarcode.MainActivity" on path: DexPathList[[zip file "/data/app/com.store.scanbarcode-5mePmYbDwc3RwRoad7s37A==/base.apk"],nativeLibraryDirectories=[/data/app/com.store.scanbarcode-5mePmYbDwc3RwRoad7s37A==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.store.scanbarcode-5mePmYbDwc3RwRoad7s37A==/base.apk because: Failure to verify dex file '/data/app/com.store.scanbarcode-5mePmYbDwc3RwRoad7s37A==/base.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:936)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5672)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        		... 6 more
`

**Comment by jenly1314** [comment]
在你项目中的build.gradle的android{}中添加如下配置：
`compileOptions {
    targetCompatibility JavaVersion.VERSION_1_8
    sourceCompatibility JavaVersion.VERSION_1_8
}`

**Comment by gavindst** [comment]
问题解决了,我只配置了系统环境变量和JavaSDK位置
十分感谢
